// Build information, automatically generated by `ng-info`
const build = {
    version: "0.0.0",
    timestamp: "Sun Sep 22 2024 16:16:09 GMT+0200 (Mitteleuropäische Sommerzeit)",
    message: null,
    git: {
        user: "daadii",
        branch: "master",
        hash: "2c9cb1",
        fullHash: "2c9cb11c6f46a449b44d9e724e54062d7712c42e"
    }
};

export default build;