// Build information, automatically generated by `ng-info`
const build = {
    version: "0.0.0",
    timestamp: "Tue Sep 24 2024 16:57:27 GMT+0200 (Mitteleuropäische Sommerzeit)",
    message: null,
    git: {
        user: "daadii",
        branch: "master",
        hash: "6ea2f8",
        fullHash: "6ea2f80e992d6f3f674416e0f3222b37fd42c04e"
    }
};

export default build;